services:
  # Frontend - Static Site
  - type: web
    name: learniq-frontend
    env: static
    rootDir: learniq-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    envVars:
      - key: VITE_API_URL
        value: https://learniq-backend-vglf.onrender.com/api/v1

  # Backend - Spring Boot API
  - type: web
    name: learniq-backend
    env: docker
    rootDir: learniq-backend
    dockerfilePath: ./Dockerfile
    plan: free

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      - key: MAIL_USERNAME
        sync: false

      - key: MAIL_PASSWORD
        sync: false

      - key: SPRING_DATASOURCE_URL
        sync: false

      - key: SPRING_DATASOURCE_USERNAME
        sync: false

      - key: SPRING_DATASOURCE_PASSWORD
        sync: false

      - key: APP_JWT_SECRET
        generateValue: true

      - key: APP_FRONTEND_URL
        value: https://learniq-frontend.onrender.com